// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace NeuralNetworkML.Model
{
    public class ModelInput
    {
        [ColumnName("type"), LoadColumn(0)]
        public string Type { get; set; }


        [ColumnName("clear_text"), LoadColumn(1)]
        public string Clear_text { get; set; }


    }
}
